# action 的名称
name: doc_pub

# 触发条件：在 push 到 docs 分支后
on:
  push:
    branches:
      - docs

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@docs
        with:
          persist-credentials: false

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: lei-mu/luch-request
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: npm install && npm run docs:build
          BUILD_DIR: docs/.vuepress/dist/

  


